// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protonyom_api_sign.proto

package gonyom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Types that are assignable to Credential:
	//	*SignUpRequest_Password
	//	*SignUpRequest_Oauthinfo
	Credential    isSignUpRequest_Credential `protobuf_oneof:"credential"`
	Oauthprovider string                     `protobuf:"bytes,5,opt,name=oauthprovider,proto3" json:"oauthprovider,omitempty"`
	Photourl      string                     `protobuf:"bytes,6,opt,name=photourl,proto3" json:"photourl,omitempty"`
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_sign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_sign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_sign_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (m *SignUpRequest) GetCredential() isSignUpRequest_Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (x *SignUpRequest) GetPassword() string {
	if x, ok := x.GetCredential().(*SignUpRequest_Password); ok {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetOauthinfo() *OAuthInfo {
	if x, ok := x.GetCredential().(*SignUpRequest_Oauthinfo); ok {
		return x.Oauthinfo
	}
	return nil
}

func (x *SignUpRequest) GetOauthprovider() string {
	if x != nil {
		return x.Oauthprovider
	}
	return ""
}

func (x *SignUpRequest) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type isSignUpRequest_Credential interface {
	isSignUpRequest_Credential()
}

type SignUpRequest_Password struct {
	Password string `protobuf:"bytes,3,opt,name=password,proto3,oneof"`
}

type SignUpRequest_Oauthinfo struct {
	Oauthinfo *OAuthInfo `protobuf:"bytes,4,opt,name=oauthinfo,proto3,oneof"`
}

func (*SignUpRequest_Password) isSignUpRequest_Credential() {}

func (*SignUpRequest_Oauthinfo) isSignUpRequest_Credential() {}

type EmailCred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *EmailCred) Reset() {
	*x = EmailCred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_sign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCred) ProtoMessage() {}

func (x *EmailCred) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_sign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCred.ProtoReflect.Descriptor instead.
func (*EmailCred) Descriptor() ([]byte, []int) {
	return file_protonyom_api_sign_proto_rawDescGZIP(), []int{1}
}

func (x *EmailCred) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailCred) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Credential:
	//	*SignInRequest_Emailcred
	//	*SignInRequest_Oauthinfo
	Credential    isSignInRequest_Credential `protobuf_oneof:"credential"`
	Oauthprovider string                     `protobuf:"bytes,3,opt,name=oauthprovider,proto3" json:"oauthprovider,omitempty"`
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_sign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_sign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_sign_proto_rawDescGZIP(), []int{2}
}

func (m *SignInRequest) GetCredential() isSignInRequest_Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (x *SignInRequest) GetEmailcred() *EmailCred {
	if x, ok := x.GetCredential().(*SignInRequest_Emailcred); ok {
		return x.Emailcred
	}
	return nil
}

func (x *SignInRequest) GetOauthinfo() *OAuthInfo {
	if x, ok := x.GetCredential().(*SignInRequest_Oauthinfo); ok {
		return x.Oauthinfo
	}
	return nil
}

func (x *SignInRequest) GetOauthprovider() string {
	if x != nil {
		return x.Oauthprovider
	}
	return ""
}

type isSignInRequest_Credential interface {
	isSignInRequest_Credential()
}

type SignInRequest_Emailcred struct {
	Emailcred *EmailCred `protobuf:"bytes,1,opt,name=emailcred,proto3,oneof"`
}

type SignInRequest_Oauthinfo struct {
	Oauthinfo *OAuthInfo `protobuf:"bytes,2,opt,name=oauthinfo,proto3,oneof"`
}

func (*SignInRequest_Emailcred) isSignInRequest_Credential() {}

func (*SignInRequest_Oauthinfo) isSignInRequest_Credential() {}

type SignReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Token   string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SignReply) Reset() {
	*x = SignReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_sign_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReply) ProtoMessage() {}

func (x *SignReply) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_sign_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReply.ProtoReflect.Descriptor instead.
func (*SignReply) Descriptor() ([]byte, []int) {
	return file_protonyom_api_sign_proto_rawDescGZIP(), []int{3}
}

func (x *SignReply) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *SignReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_protonyom_api_sign_proto protoreflect.FileDescriptor

var file_protonyom_api_sign_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x5f,
	0x73, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdd, 0x01,
	0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x34, 0x0a, 0x09, 0x6f, 0x61, 0x75, 0x74, 0x68,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x48, 0x00, 0x52, 0x09, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a,
	0x0d, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x75, 0x72, 0x6c, 0x42,
	0x0c, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x3d, 0x0a,
	0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xaf, 0x01, 0x0a,
	0x0d, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x09, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x63, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x43, 0x72, 0x65, 0x64, 0x48, 0x00, 0x52, 0x09, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x63, 0x72, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x09, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e,
	0x79, 0x6f, 0x6d, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52,
	0x09, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x61,
	0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x42, 0x0c, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x4f,
	0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32,
	0xbe, 0x01, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x41, 0x70, 0x69, 0x12, 0x3a, 0x0a, 0x06, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f,
	0x6d, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75, 0x74, 0x12, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79,
	0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x00,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x69, 0x63, 0x65, 0x72, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protonyom_api_sign_proto_rawDescOnce sync.Once
	file_protonyom_api_sign_proto_rawDescData = file_protonyom_api_sign_proto_rawDesc
)

func file_protonyom_api_sign_proto_rawDescGZIP() []byte {
	file_protonyom_api_sign_proto_rawDescOnce.Do(func() {
		file_protonyom_api_sign_proto_rawDescData = protoimpl.X.CompressGZIP(file_protonyom_api_sign_proto_rawDescData)
	})
	return file_protonyom_api_sign_proto_rawDescData
}

var file_protonyom_api_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protonyom_api_sign_proto_goTypes = []interface{}{
	(*SignUpRequest)(nil), // 0: protonyom.SignUpRequest
	(*EmailCred)(nil),     // 1: protonyom.EmailCred
	(*SignInRequest)(nil), // 2: protonyom.SignInRequest
	(*SignReply)(nil),     // 3: protonyom.SignReply
	(*OAuthInfo)(nil),     // 4: protonyom.OAuthInfo
	(*Account)(nil),       // 5: protonyom.Account
	(*EmptyParams)(nil),   // 6: protonyom.EmptyParams
}
var file_protonyom_api_sign_proto_depIdxs = []int32{
	4, // 0: protonyom.SignUpRequest.oauthinfo:type_name -> protonyom.OAuthInfo
	1, // 1: protonyom.SignInRequest.emailcred:type_name -> protonyom.EmailCred
	4, // 2: protonyom.SignInRequest.oauthinfo:type_name -> protonyom.OAuthInfo
	5, // 3: protonyom.SignReply.account:type_name -> protonyom.Account
	2, // 4: protonyom.SignApi.SignIn:input_type -> protonyom.SignInRequest
	0, // 5: protonyom.SignApi.SignUp:input_type -> protonyom.SignUpRequest
	6, // 6: protonyom.SignApi.SignOut:input_type -> protonyom.EmptyParams
	3, // 7: protonyom.SignApi.SignIn:output_type -> protonyom.SignReply
	3, // 8: protonyom.SignApi.SignUp:output_type -> protonyom.SignReply
	6, // 9: protonyom.SignApi.SignOut:output_type -> protonyom.EmptyParams
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protonyom_api_sign_proto_init() }
func file_protonyom_api_sign_proto_init() {
	if File_protonyom_api_sign_proto != nil {
		return
	}
	file_protonyom_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protonyom_api_sign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_sign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailCred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_sign_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_sign_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protonyom_api_sign_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SignUpRequest_Password)(nil),
		(*SignUpRequest_Oauthinfo)(nil),
	}
	file_protonyom_api_sign_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SignInRequest_Emailcred)(nil),
		(*SignInRequest_Oauthinfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protonyom_api_sign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protonyom_api_sign_proto_goTypes,
		DependencyIndexes: file_protonyom_api_sign_proto_depIdxs,
		MessageInfos:      file_protonyom_api_sign_proto_msgTypes,
	}.Build()
	File_protonyom_api_sign_proto = out.File
	file_protonyom_api_sign_proto_rawDesc = nil
	file_protonyom_api_sign_proto_goTypes = nil
	file_protonyom_api_sign_proto_depIdxs = nil
}
