// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protonyom_api_pet.proto

package gonyom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Family struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Species map[string]string `protobuf:"bytes,2,rep,name=species,proto3" json:"species,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Family) Reset() {
	*x = Family{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{0}
}

func (x *Family) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Family) GetSpecies() map[string]string {
	if x != nil {
		return x.Species
	}
	return nil
}

type GetFamiliesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *GetFamiliesRequest) Reset() {
	*x = GetFamiliesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFamiliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamiliesRequest) ProtoMessage() {}

func (x *GetFamiliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamiliesRequest.ProtoReflect.Descriptor instead.
func (*GetFamiliesRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{1}
}

func (x *GetFamiliesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetFamiliesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Families map[string]*Family `protobuf:"bytes,1,rep,name=families,proto3" json:"families,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetFamiliesReply) Reset() {
	*x = GetFamiliesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFamiliesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamiliesReply) ProtoMessage() {}

func (x *GetFamiliesReply) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamiliesReply.ProtoReflect.Descriptor instead.
func (*GetFamiliesReply) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{2}
}

func (x *GetFamiliesReply) GetFamilies() map[string]*Family {
	if x != nil {
		return x.Families
	}
	return nil
}

type AddPetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet                *Pet   `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	ProfilePhoto       []byte `protobuf:"bytes,2,opt,name=profilePhoto,proto3" json:"profilePhoto,omitempty"`
	ProfileContentType string `protobuf:"bytes,3,opt,name=profileContentType,proto3" json:"profileContentType,omitempty"`
}

func (x *AddPetRequest) Reset() {
	*x = AddPetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetRequest) ProtoMessage() {}

func (x *AddPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetRequest.ProtoReflect.Descriptor instead.
func (*AddPetRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{3}
}

func (x *AddPetRequest) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

func (x *AddPetRequest) GetProfilePhoto() []byte {
	if x != nil {
		return x.ProfilePhoto
	}
	return nil
}

func (x *AddPetRequest) GetProfileContentType() string {
	if x != nil {
		return x.ProfileContentType
	}
	return ""
}

type AddPetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Pets    []*Pet   `protobuf:"bytes,2,rep,name=pets,proto3" json:"pets,omitempty"`
}

func (x *AddPetReply) Reset() {
	*x = AddPetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetReply) ProtoMessage() {}

func (x *AddPetReply) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetReply.ProtoReflect.Descriptor instead.
func (*AddPetReply) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{4}
}

func (x *AddPetReply) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AddPetReply) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type UpdatePetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet                *Pet   `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	ProfilePhoto       []byte `protobuf:"bytes,2,opt,name=profilePhoto,proto3" json:"profilePhoto,omitempty"`
	ProfileContentType string `protobuf:"bytes,3,opt,name=profileContentType,proto3" json:"profileContentType,omitempty"`
}

func (x *UpdatePetRequest) Reset() {
	*x = UpdatePetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetRequest) ProtoMessage() {}

func (x *UpdatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePetRequest) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

func (x *UpdatePetRequest) GetProfilePhoto() []byte {
	if x != nil {
		return x.ProfilePhoto
	}
	return nil
}

func (x *UpdatePetRequest) GetProfileContentType() string {
	if x != nil {
		return x.ProfileContentType
	}
	return ""
}

type UpdatePetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pets []*Pet `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
}

func (x *UpdatePetReply) Reset() {
	*x = UpdatePetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetReply) ProtoMessage() {}

func (x *UpdatePetReply) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetReply.ProtoReflect.Descriptor instead.
func (*UpdatePetReply) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePetReply) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type DeletePetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PetId string `protobuf:"bytes,1,opt,name=petId,proto3" json:"petId,omitempty"`
}

func (x *DeletePetRequest) Reset() {
	*x = DeletePetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetRequest) ProtoMessage() {}

func (x *DeletePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetRequest.ProtoReflect.Descriptor instead.
func (*DeletePetRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type DeletePetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Pets    []*Pet   `protobuf:"bytes,2,rep,name=pets,proto3" json:"pets,omitempty"`
}

func (x *DeletePetReply) Reset() {
	*x = DeletePetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetReply) ProtoMessage() {}

func (x *DeletePetReply) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetReply.ProtoReflect.Descriptor instead.
func (*DeletePetReply) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePetReply) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *DeletePetReply) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type GetPetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PetIds []string `protobuf:"bytes,1,rep,name=petIds,proto3" json:"petIds,omitempty"`
}

func (x *GetPetListRequest) Reset() {
	*x = GetPetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetListRequest) ProtoMessage() {}

func (x *GetPetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetListRequest.ProtoReflect.Descriptor instead.
func (*GetPetListRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{9}
}

func (x *GetPetListRequest) GetPetIds() []string {
	if x != nil {
		return x.PetIds
	}
	return nil
}

type GetPetListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pets []*Pet `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
}

func (x *GetPetListReply) Reset() {
	*x = GetPetListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetListReply) ProtoMessage() {}

func (x *GetPetListReply) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetListReply.ProtoReflect.Descriptor instead.
func (*GetPetListReply) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{10}
}

func (x *GetPetListReply) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type GetPetWithFeedsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PetId string `protobuf:"bytes,1,opt,name=petId,proto3" json:"petId,omitempty"`
}

func (x *GetPetWithFeedsRequest) Reset() {
	*x = GetPetWithFeedsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetWithFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetWithFeedsRequest) ProtoMessage() {}

func (x *GetPetWithFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetWithFeedsRequest.ProtoReflect.Descriptor instead.
func (*GetPetWithFeedsRequest) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{11}
}

func (x *GetPetWithFeedsRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type GetPetWithFeedsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PetFeeds *PetFeeds `protobuf:"bytes,1,opt,name=petFeeds,proto3" json:"petFeeds,omitempty"`
}

func (x *GetPetWithFeedsReply) Reset() {
	*x = GetPetWithFeedsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonyom_api_pet_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetWithFeedsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetWithFeedsReply) ProtoMessage() {}

func (x *GetPetWithFeedsReply) ProtoReflect() protoreflect.Message {
	mi := &file_protonyom_api_pet_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetWithFeedsReply.ProtoReflect.Descriptor instead.
func (*GetPetWithFeedsReply) Descriptor() ([]byte, []int) {
	return file_protonyom_api_pet_proto_rawDescGZIP(), []int{12}
}

func (x *GetPetWithFeedsReply) GetPetFeeds() *PetFeeds {
	if x != nil {
		return x.PetFeeds
	}
	return nil
}

var File_protonyom_api_pet_proto protoreflect.FileDescriptor

var file_protonyom_api_pet_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x5f,
	0x70, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6e, 0x79, 0x6f, 0x6d, 0x1a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a,
	0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x30, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x1a,
	0x4e, 0x0a, 0x0d, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x85, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x03,
	0x70, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5f, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e,
	0x79, 0x6f, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x50,
	0x65, 0x74, 0x52, 0x04, 0x70, 0x65, 0x74, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x03, 0x70, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x03, 0x70, 0x65, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x12, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x34, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e,
	0x50, 0x65, 0x74, 0x52, 0x04, 0x70, 0x65, 0x74, 0x73, 0x22, 0x28, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65,
	0x74, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79,
	0x6f, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x50, 0x65,
	0x74, 0x52, 0x04, 0x70, 0x65, 0x74, 0x73, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x65, 0x74, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65,
	0x74, 0x49, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x65, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f,
	0x6d, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x04, 0x70, 0x65, 0x74, 0x73, 0x22, 0x2e, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x46, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x46, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f,
	0x6d, 0x2e, 0x50, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x73, 0x52, 0x08, 0x70, 0x65, 0x74, 0x46,
	0x65, 0x65, 0x64, 0x73, 0x32, 0xc4, 0x03, 0x0a, 0x06, 0x50, 0x65, 0x74, 0x41, 0x70, 0x69, 0x12,
	0x4b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x06,
	0x41, 0x64, 0x64, 0x50, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79,
	0x6f, 0x6d, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x41, 0x64, 0x64,
	0x50, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x09, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e,
	0x79, 0x6f, 0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x74, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79,
	0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x57, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68,
	0x46, 0x65, 0x65, 0x64, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x46, 0x65, 0x65, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6e, 0x79, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x46,
	0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x63, 0x65, 0x72, 0x75,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x79, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6e, 0x79, 0x6f,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protonyom_api_pet_proto_rawDescOnce sync.Once
	file_protonyom_api_pet_proto_rawDescData = file_protonyom_api_pet_proto_rawDesc
)

func file_protonyom_api_pet_proto_rawDescGZIP() []byte {
	file_protonyom_api_pet_proto_rawDescOnce.Do(func() {
		file_protonyom_api_pet_proto_rawDescData = protoimpl.X.CompressGZIP(file_protonyom_api_pet_proto_rawDescData)
	})
	return file_protonyom_api_pet_proto_rawDescData
}

var file_protonyom_api_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protonyom_api_pet_proto_goTypes = []interface{}{
	(*Family)(nil),                 // 0: protonyom.Family
	(*GetFamiliesRequest)(nil),     // 1: protonyom.GetFamiliesRequest
	(*GetFamiliesReply)(nil),       // 2: protonyom.GetFamiliesReply
	(*AddPetRequest)(nil),          // 3: protonyom.AddPetRequest
	(*AddPetReply)(nil),            // 4: protonyom.AddPetReply
	(*UpdatePetRequest)(nil),       // 5: protonyom.UpdatePetRequest
	(*UpdatePetReply)(nil),         // 6: protonyom.UpdatePetReply
	(*DeletePetRequest)(nil),       // 7: protonyom.DeletePetRequest
	(*DeletePetReply)(nil),         // 8: protonyom.DeletePetReply
	(*GetPetListRequest)(nil),      // 9: protonyom.GetPetListRequest
	(*GetPetListReply)(nil),        // 10: protonyom.GetPetListReply
	(*GetPetWithFeedsRequest)(nil), // 11: protonyom.GetPetWithFeedsRequest
	(*GetPetWithFeedsReply)(nil),   // 12: protonyom.GetPetWithFeedsReply
	nil,                            // 13: protonyom.Family.SpeciesEntry
	nil,                            // 14: protonyom.GetFamiliesReply.FamiliesEntry
	(*Pet)(nil),                    // 15: protonyom.Pet
	(*Account)(nil),                // 16: protonyom.Account
	(*PetFeeds)(nil),               // 17: protonyom.PetFeeds
}
var file_protonyom_api_pet_proto_depIdxs = []int32{
	13, // 0: protonyom.Family.species:type_name -> protonyom.Family.SpeciesEntry
	14, // 1: protonyom.GetFamiliesReply.families:type_name -> protonyom.GetFamiliesReply.FamiliesEntry
	15, // 2: protonyom.AddPetRequest.pet:type_name -> protonyom.Pet
	16, // 3: protonyom.AddPetReply.account:type_name -> protonyom.Account
	15, // 4: protonyom.AddPetReply.pets:type_name -> protonyom.Pet
	15, // 5: protonyom.UpdatePetRequest.pet:type_name -> protonyom.Pet
	15, // 6: protonyom.UpdatePetReply.pets:type_name -> protonyom.Pet
	16, // 7: protonyom.DeletePetReply.account:type_name -> protonyom.Account
	15, // 8: protonyom.DeletePetReply.pets:type_name -> protonyom.Pet
	15, // 9: protonyom.GetPetListReply.pets:type_name -> protonyom.Pet
	17, // 10: protonyom.GetPetWithFeedsReply.petFeeds:type_name -> protonyom.PetFeeds
	0,  // 11: protonyom.GetFamiliesReply.FamiliesEntry.value:type_name -> protonyom.Family
	1,  // 12: protonyom.PetApi.GetFamilies:input_type -> protonyom.GetFamiliesRequest
	3,  // 13: protonyom.PetApi.AddPet:input_type -> protonyom.AddPetRequest
	5,  // 14: protonyom.PetApi.UpdatePet:input_type -> protonyom.UpdatePetRequest
	7,  // 15: protonyom.PetApi.DeletePet:input_type -> protonyom.DeletePetRequest
	9,  // 16: protonyom.PetApi.GetPetList:input_type -> protonyom.GetPetListRequest
	11, // 17: protonyom.PetApi.GetPetWithFeeds:input_type -> protonyom.GetPetWithFeedsRequest
	2,  // 18: protonyom.PetApi.GetFamilies:output_type -> protonyom.GetFamiliesReply
	4,  // 19: protonyom.PetApi.AddPet:output_type -> protonyom.AddPetReply
	6,  // 20: protonyom.PetApi.UpdatePet:output_type -> protonyom.UpdatePetReply
	8,  // 21: protonyom.PetApi.DeletePet:output_type -> protonyom.DeletePetReply
	10, // 22: protonyom.PetApi.GetPetList:output_type -> protonyom.GetPetListReply
	12, // 23: protonyom.PetApi.GetPetWithFeeds:output_type -> protonyom.GetPetWithFeedsReply
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protonyom_api_pet_proto_init() }
func file_protonyom_api_pet_proto_init() {
	if File_protonyom_api_pet_proto != nil {
		return
	}
	file_protonyom_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protonyom_api_pet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Family); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFamiliesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFamiliesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetWithFeedsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonyom_api_pet_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetWithFeedsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protonyom_api_pet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protonyom_api_pet_proto_goTypes,
		DependencyIndexes: file_protonyom_api_pet_proto_depIdxs,
		MessageInfos:      file_protonyom_api_pet_proto_msgTypes,
	}.Build()
	File_protonyom_api_pet_proto = out.File
	file_protonyom_api_pet_proto_rawDesc = nil
	file_protonyom_api_pet_proto_goTypes = nil
	file_protonyom_api_pet_proto_depIdxs = nil
}
